version: "3.9"

services:
  code:
    image: paveldedik/code-server:3.9.0
    build:
      context: ./
      dockerfile: ./Dockerfile
      cache_from:
        - paveldedik/code-server:latest
    volumes:
      - //e/code/project:/home/coder/project
      - //c/Users/dedik/.config:/home/coder/.config
    environment:
      - USER=dedik
      - DOCKER_USER=dedik
    restart: unless-stopped

  nginx:
    image: nginx:latest
    ports:
      - 0.0.0.0:80:80
      - 0.0.0.0:443:443
    volumes:
      - //e/code/server/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - //c/Certbot:/cert
    restart: unless-stopped
